# Generated by Django 4.0.5 on 2022-06-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortenUrl',
            fields=[
                ('shorten', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('originLink', models.CharField(max_length=9999)),
            ],
        ),
    ]
