name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2.0.0
      with:
        username: ${{ secrets.DOCKERHUB_USER}}
        password: ${{ secrets.DOCKERHUB_TOKEN}}
    
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: spraus/omni-test

    - name: Publish 
      uses: docker/build-push-action@v3.0.0
      with:   
        context: .
        push: true
        tags: spraus/omni-test:latest
        labels: ${{ steps.meta.outputs.labels }}
